**Write a program for implementing Dcitonary**


In [ ]:
#Creating dictionary
dic = {"meghana":1,"shruthi":2,"Anjana":3}
print(dic)

{'meghana': 1, 'shruthi': 2, 'Anjana': 3}


In [ ]:
#Accessing and updating Dictionary
dic = {"meghana":1,"shruthi":2,"Anjana":3}
dic["Hari"] = 4
print(dic)
dic["Kausthubh"] = 15
print(dic)

{'meghana': 1, 'shruthi': 2, 'Anjana': 3, 'Hari': 4}
{'meghana': 1, 'shruthi': 2, 'Anjana': 3, 'Hari': 4, 'Kausthubh': 15}


In [ ]:
# Deleting Dictionary
del dic["shruthi"]
print(dic)

{'meghana': 1, 'Anjana': 3, 'Hari': 4, 'Kausthubh': 15}


In [ ]:
# Copy Dictionary
Mydict = {
    'Name':"Meghana",
    "Branch":"AI",
    "Year":2
}
Updatedict = Mydict.copy()
print(Updatedict)

{'Name': 'Meghana', 'Branch': 'AI', 'Year': 2}


In [ ]:
# Dictionary Comprehension
squares = {x:x*x for x in range (6)}
print(squares)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [ ]:
squares = {}
for x in range (3):
  squares[x] = x*x
  print(squares)

{0: 0}
{0: 0, 1: 1}
{0: 0, 1: 1, 2: 4}


In [ ]:
# Iterating through a dictonary
squares = {1:1,3:9,4:16,5:25}
for i in squares:
    print(squares[i])

1
9
16
25


**Write a Program for calculating with matrices using numpy**

**inv**

In [ ]:
import numpy as np
A = np.array([[1,2,3],
              [-3,-1,3],
              [2,9,-4]])
print(np.linalg.inv(A))

[[ 0.20909091 -0.31818182 -0.08181818]
 [ 0.05454545  0.09090909  0.10909091]
 [ 0.22727273  0.04545455 -0.04545455]]


**pinv**

In [ ]:
print(np.linalg.pinv(A))

[[-0.23  0.35  0.09]
 [ 0.18 -0.1   0.06]
 [ 0.29 -0.05 -0.07]]


In [ ]:
import numpy as np
A = np.array([[1,3],
              [2,6]])
print(np.linalg.inv(A))
# It returns error as inv doesnt deal with singular matrix

LinAlgError: ignored

In [ ]:
import numpy as np
A = np.array([[1,3],
              [2,6]])
print(np.linalg.pinv(A))

[[0.02 0.04]
 [0.06 0.12]]


**Matrix rank**

In [ ]:
print(np.linalg.matrix_rank(A))

3


**LSTSQ**

In [ ]:
x = np.array([[0, 1], [2, 3]])
y = np.array([[1, 0.2], [2.1, 2.1]])
np.linalg.lstsq(x,y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([[-0.45,  0.75],
        [ 1.  ,  0.2 ]]),
 array([], dtype=float64),
 2,
 array([3.70245917, 0.54018151]))

**SVG**

In [ ]:
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
b = np.random.randn(2, 7, 8, 3) + 1j*np.random.randn(2, 7, 8, 3)
m, n, vh = np.linalg.svd(a, full_matrices=True)
m.shape, n.shape, vh.shape

((9, 9), (6,), (6, 6))

**Transpose**

In [ ]:
a = np.array([[1, 2], [3, 4]])
a.transpose()

array([[1, 3],
       [2, 4]])

**EIG**

In [ ]:
from numpy import linalg as LA
w, v = LA.eig(np.diag((1, 2, 3)))
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**sort**

In [ ]:
a = np.array([[1,4],[3,1]])
np.sort(a) 

array([[1, 4],
       [1, 3]])

**linspace**

In [ ]:
a=np.linspace(2.0, 3.0, num=7)
a

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333, 3.        ])